name: MongoDB Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set PYTHONPATH and Environment Variables
      run: |
        echo "PYTHONPATH=$PWD/Cases/homeobjects:$PWD/Cases/login_testcases:$PWD/Cases/configfile" >> $GITHUB_ENV
        echo "MONGO_URI=mongodb://127.0.0.1:27017/sampleupload" >> $GITHUB_ENV

    - name: Start MongoDB Service
      run: |
        sudo systemctl start mongodb
        sudo systemctl status mongodb

    - name: Wait for MongoDB to be Ready
      run: |
        until nc -zv localhost 27017; do
          echo "Waiting for MongoDB to start..."
          sleep 1
        done
        echo "MongoDB is ready"

    - name: Configure MongoDB Test Data
      run: |
        python Cases/configfile/config.py  # Adjust this path as needed for your project

    - name: Verify MongoDB Data
      run: |
        echo "Checking MongoDB contents..."
        mongo --eval "db = connect('localhost:27017/sampleupload'); printjson(db.users.find().toArray())"

    - name: Run Application Tests
      run: |
        echo "Running application tests..."
        # Add commands to run your application tests, for example:
        python Cases/tests/run_tests.py
